### ISSUE TITLE
Make run not working

### ISSUE THREAD

**Issue by LuisNievesRosado** [SpakowitzLab/wlcsim#10]
When I try to run a simulation using make run, I get the following output:

> $ make run
> /bin/bash: - : invalid option
> Usage:  /bin/bash [GNU long option] [option] ...
>         /bin/bash [GNU long option] [option] script-file ...
> GNU long options:
>         --debug
>         --debugger
>         --dump-po-strings
>         --dump-strings
>         --help
>         --init-file
>         --login
>         --noediting
>         --noprofile
>         --norc
>         --posix
>         --protected
>         --rcfile
>         --restricted
>         --verbose
>         --version
>         --wordexp
> Shell options:
>         -ilrsD or -c command or -O shopt_option         (invocation only)
>         -abefhkmnptuvxBCHP or -o option
> make: **\* [Makefile:79: wlcsim.dep] Error 2

Not sure what is the source of if this error. 

I'm using Cygwin and have GNU Make version 4.2.1

**Comment by brunobeltran** [comment]
Closed by #11
